import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createNavigation} from '../src/navigation.js';
import {makeTask,taskStep,advanceTask,PLACES,EVENTS,rating} from '../src/simulation.js';
const layout=JSON.parse(readFileSync(new URL('../public/assets/navigation.json',import.meta.url)));
const nav=createNavigation(layout.obstacles,.25,layout);
test('all rooms and chore stations are reachable from the connected living space without crossing furniture',()=>{for(const p of [...layout.rooms,...Object.values(PLACES)]){const route=nav.path({x:0,z:0},p);assert.ok(route.length>0,JSON.stringify(p));assert.ok(route.every(q=>!nav.blocked(q.x,q.z)));const end=route.at(-1);assert.ok(Math.hypot(end.x-p.x,end.z-p.z)<1,p.name+' target is too far from walkable space')}});
test('snacks require preparation, collection, then delivery',()=>{const t=makeTask(1,'snack',0);const kid={name:'Jax',x:3,z:3};assert.equal(taskStep(t,kid).name,'Kitchen');assert.equal(advanceTask(t),false);assert.equal(taskStep(t,kid).name,'Jax');assert.equal(advanceTask(t),false);assert.equal(taskStep(t,kid).name,'Dining room');assert.equal(advanceTask(t),true)});
test('every chore has usable stages and completes exactly once at the final stage',()=>{for(const type of Object.keys(EVENTS)){const t=makeTask(1,type,0);for(let i=0;i<EVENTS[type].steps;i++){const s=taskStep(t,{name:'Harper',x:0,z:0});assert.ok(s.duration>0);assert.ok(Number.isFinite(s.x)&&Number.isFinite(s.z));assert.equal(advanceTask(t),i===EVENTS[type].steps-1)}}});
test('difficulty never gives less than 28 seconds and stars reward completed care',()=>{assert.equal(makeTask(1,'spill',0,false,99).total,28);assert.equal(rating(9,0),3);assert.equal(rating(6,1),2);assert.equal(rating(0,8),1)});
test('Blender exports are valid GLB v2 assets with actual mesh data',()=>{for(const n of ['house','kayla','harper','jax','arianna','lilah']){const b=readFileSync(new URL('../public/assets/'+n+'.glb',import.meta.url));assert.equal(b.toString('ascii',0,4),'glTF');assert.equal(b.readUInt32LE(4),2);assert.equal(b.readUInt32LE(8),b.length);const j=JSON.parse(b.toString('utf8',20,20+b.readUInt32LE(12)));assert.ok(j.meshes.length>0);assert.ok(j.asset.generator.includes('Blender'))}});
test('characters retain articulated joints and requested vertex-painted hair colors',()=>{for(const [name,hair] of Object.entries({kayla:'dec078',harper:'e5c779',jax:'ebd493',arianna:'654337',lilah:'dfbd71'})){const b=readFileSync(new URL('../public/assets/'+name+'.glb',import.meta.url));const size=b.readUInt32LE(12),j=JSON.parse(b.toString('utf8',20,20+size));for(const n of ['head','armL','armR','foreL','foreR','legL','legR','shinL','shinR'])assert.ok(j.nodes.some(o=>o.name===n+'_'+name));const head=j.meshes[j.nodes.find(n=>n.name===name+'_head_mesh').mesh];const a=j.accessors[head.primitives[0].attributes.COLOR_0],v=j.bufferViews[a.bufferView],offset=28+size+(v.byteOffset||0)+(a.byteOffset||0);const expected=[0,2,4].map(i=>{const v=parseInt(hair.slice(i,i+2),16)/255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4});let found=false;for(let i=0;i<a.count;i++){if(expected.every((color,c)=>Math.abs(color-b.readFloatLE(offset+i*(v.byteStride||12)+c*4))<.002)){found=true;break}}assert.ok(found,name+' hair vertex color');}});

import {pose,choreMode} from '../src/animation.js';
test('walking articulates opposing legs and bends a knee',()=>{const p=pose('walk',0,Math.PI/2);assert.ok(p.legL>0&&p.legR<0);assert.ok(p.shinR>0);assert.ok(p.armL<0&&p.armR>0)});
test('every chore has a visible distinct activity and animation changes over time',()=>{for(const type of Object.keys(EVENTS)){const mode=choreMode(type,0);assert.notEqual(mode,'idle');assert.notDeepEqual(pose(mode,.1),pose(mode,.6));}assert.notDeepEqual(pose('selfie',0),pose('idle',0));assert.notDeepEqual(pose('sleep',0),pose('eat',0))});
test('yard and fenced pool stay outside the indoor navigation mesh',()=>{assert.ok(nav.blocked(1,-16));assert.ok(nav.blocked(-11,7));for(const a of layout.rooms)for(const b of layout.rooms)assert.ok(nav.path(a,b).length,a.name+' to '+b.name)});
