import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {mergeVertices,mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {createNavigation} from './navigation.js';
import {KIDS,EVENTS,PLACES,makeTask,taskStep,advanceTask,rating} from './simulation.js';
import {bindRig,animateActor,choreMode} from './animation.js';
import {ChoreEffects} from './effects.js';
import './modern.css';
const $=id=>document.getElementById(id),app=$('app');
let renderer;try{renderer=new THREE.WebGLRenderer({canvas:$('game'),antialias:true,alpha:false,powerPreference:'high-performance'});}catch(e){$('start').textContent='This browser needs WebGL 2';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor('#a6c9db');renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;
const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-8,8,14,-14,.1,100);camera.position.set(18,20,18);camera.lookAt(0,0,0);
scene.add(new THREE.HemisphereLight('#fff8e4','#b6a5b8',1.65));const sun=new THREE.DirectionalLight('#fff0df',2.15);sun.position.set(-8,20,10);scene.add(sun);
const world=new THREE.Group();scene.add(world);
let width=400,height=800,closeView=false;function resize(){width=app.clientWidth;height=app.clientHeight;renderer.setSize(width,height,false);const vh=closeView?Math.max(17.5,8.3/(width/height)):Math.max(43,31/(width/height));camera.left=-vh*width/height/2;camera.right=-camera.left;camera.top=vh/2+.4;camera.bottom=-vh/2+.4;camera.updateProjectionMatrix();document.body.classList.toggle('landscape',innerWidth>innerHeight)}window.addEventListener('resize',resize);resize();
const viewButton=document.createElement('button');viewButton.id='view';viewButton.textContent='⌑';viewButton.setAttribute('aria-label','Toggle house overview');$('pause').before(viewButton);viewButton.onclick=()=>{closeView=!closeView;viewButton.textContent=closeView?'⌑':'＋';resize()};
// One shared soft contact-shadow texture, instead of expensive realtime shadow maps.
const sc=document.createElement('canvas');sc.width=sc.height=64;const ctx=sc.getContext('2d'),grad=ctx.createRadialGradient(32,32,3,32,32,30);grad.addColorStop(0,'rgba(65,61,41,.3)');grad.addColorStop(1,'rgba(65,61,41,0)');ctx.fillStyle=grad;ctx.fillRect(0,0,64,64);const shadowTex=new THREE.CanvasTexture(sc),shadowMat=new THREE.MeshBasicMaterial({map:shadowTex,transparent:true,depthWrite:false});
function shadow(x,z,size){const m=new THREE.Mesh(new THREE.PlaneGeometry(size,size),shadowMat);m.rotation.x=-Math.PI/2;m.position.set(x,.11,z);world.add(m);return m}
const labelItems=[];function label(text,position,cls=''){const el=document.createElement('div');el.className='label '+cls;el.textContent=text;$('labels').append(el);const item={el,position};labelItems.push(item);return item}
let nav,rooms,kids=[],player,ready=false,running=false,paused=false,cozy=false,day=1,seconds=180,happiness=100,score=0,completed=0,missed=0,combo=0,tasks=[],selected=null,sequence=0,spawnIn=9,elapsed=0,toastUntil=0,hold=false,soundOn=false,lowQuality=false;
let audioCtx;function chime(success=true){if(!soundOn)return;try{audioCtx??=new AudioContext();audioCtx.resume();for(let i=0;i<3;i++){const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.connect(g);g.connect(audioCtx.destination);o.type='sine';o.frequency.value=(success?523:220)*[1,1.25,1.5][i];const t=audioCtx.currentTime+i*.08;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.05,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+.2);o.start(t);o.stop(t+.22)}}catch{}}
function toast(text){if(!text)return;$('toast').textContent=text;$('toast').classList.add('show');toastUntil=performance.now()+2200}
const v=new THREE.Vector3();
const toyMaterial=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.78});
let effects,workingNow=false,socialActive=false,socialWork=0,socialCooldown=0,posts=0;
const captions=['A peaceful morning. The sofa has entered orbit.','Meal prep complete. Jax reviewed it: NANA!','My assistant folded one sock. Then wore it as a hat.','Spa day! The client requested seventeen rubber ducks.','House tour: the carpet is apparently an ocean.'];
const postButton=document.createElement('button');postButton.id='post';postButton.textContent='📱';postButton.hidden=true;postButton.setAttribute('aria-label','Take a funny in-game selfie. Timers keep running. Keyboard P');$('pause').before(postButton);
postButton.onclick=()=>{if(!running||paused||socialCooldown>0)return;socialActive=!socialActive;socialWork=0;if(socialActive){selected=null;player.path=[];toast('A quick MomLife post? Hold to pose!')}updateTasks()};
function paint(root){root.traverse(o=>{if(o.isMesh){o.material=toyMaterial;o.castShadow=false;o.receiveShadow=false}})}
function optimize(root){root.updateMatrixWorld(true);const pieces=[];root.traverse(o=>{if(o.isMesh){const g=o.geometry.clone().applyMatrix4(o.matrixWorld).toNonIndexed();if(!g.attributes.color){const colors=new Float32Array(g.attributes.position.count*3).fill(1);g.setAttribute('color',new THREE.BufferAttribute(colors,3));}g.deleteAttribute('uv');g.deleteAttribute('tangent');g.clearGroups();pieces.push(g)}});const mesh=new THREE.Mesh(mergeVertices(mergeGeometries(pieces,false)),toyMaterial);root.clear();root.add(mesh);pieces.forEach(g=>g.dispose())}
const loader=new GLTFLoader();
async function loadModel(url){
 if(typeof DecompressionStream==='undefined')return loader.loadAsync(url);
 const response=await fetch(url+'.gz');if(!response.ok)return loader.loadAsync(url);
 let buffer=await response.arrayBuffer();const bytes=new Uint8Array(buffer);
 // Some hosts decode gzip automatically; recognize the GLB magic before decoding.
 if(bytes[0]===31&&bytes[1]===139)buffer=await new Response(new Blob([buffer]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();
 return loader.parseAsync(buffer,'/assets/');
}
async function init(){
 const [house,navigation,props,...models]=await Promise.all([loadModel('/assets/house.glb'),fetch('/assets/navigation.json').then(r=>{if(!r.ok)throw Error('Missing navigation');return r.json()}),loadModel('/assets/props.glb'),...['kayla',...KIDS.map(k=>k.id)].map(n=>loadModel('/assets/'+n+'.glb'))]);
 optimize(house.scene);world.add(house.scene);rooms=navigation.rooms;nav=createNavigation(navigation.obstacles,.25,navigation);paint(props.scene);effects=new ChoreEffects(world,props.scene);
 for(const [x,z,w,d] of navigation.obstacles){if(w>.5&&d>.4)shadow(x,z,Math.max(w,d)*1.35)}
 rooms.forEach(r=>label(r.name.toUpperCase(),()=>({x:r.x,y:.18,z:r.z+1.96}),'room-label'));
 function actor(model,name,x,z,scale=1){paint(model.scene);const object=model.scene;object.position.set(x,0,z);object.scale.setScalar(scale);world.add(object);const a={object,rig:bindRig(object,name.toLowerCase()),name,x,z,path:[],phase:Math.random()*6,moving:false,shadow:shadow(x,z,.85)};a.lids=effects.prop('eyelids');a.rig.head.add(a.lids);a.lids.visible=false;a.label=label(name,()=>({x:a.object.position.x,y:a.object.position.y+(name==='Kayla'?2.35:1.8),z:a.object.position.z}),name==='Kayla'?'kayla':'');return a}
 player=actor(models[0],'Kayla',-1,0);player.object.rotation.y=Math.PI/4;kids=KIDS.map((k,i)=>{const r=rooms[k.room],p=nav.nearest({x:r.x+1,z:r.z+.5+i*.22});return {...actor(models[i+1],k.name,p.x,p.z),...k,timer:3+i*2,task:null,sleep:0,follow:false}});
 ready=true;$('start').disabled=$('cozy').disabled=false;$('start').textContent='Start the day →';renderer.render(scene,camera);
}
init().catch(error=>{console.error(error);$('start').textContent='Couldn’t load the house · tap to retry';$('start').disabled=false;$('start').onclick=()=>location.reload();toast('Asset loading failed. Check your connection and try again.');});
function start(isCozy=false){if(!ready)return;cozy=isCozy;closeView=true;resize();effects.clear();socialActive=false;socialCooldown=0;socialWork=posts=0;effects.hold(player,null);cozy=isCozy;running=true;paused=false;seconds=180;happiness=100;score=completed=missed=combo=elapsed=0;tasks=[];selected=null;sequence=0;spawnIn=10;player.x=-1;player.z=0;player.object.rotation.y=Math.PI/4;player.path=[];kids.forEach(k=>{k.task=null;k.sleep=0;k.rest=null;k.action=null;k.seat=null;k.follow=false;k.path=[];k.timer=4;const p=nav.nearest({x:rooms[k.room].x+(k.id==='lilah'?-.25:1),z:rooms[k.room].z+(k.id==='lilah'?1.3:.8)});k.x=p.x;k.z=p.z});for(const id of ['overlay','pauseOverlay','endOverlay'])$(id).classList.add('hidden');spawn('snack',1);spawn('art',0);updateTasks();}
function spawn(type,index){if(tasks.length>=5)return;let kid=index===undefined?kids.filter(k=>!k.task&&k.sleep<=0)[Math.floor(Math.random()*kids.filter(k=>!k.task&&k.sleep<=0).length)]:kids[index];if(!kid)return;
 if(!type){const bag=kid.id==='harper'?['art','dance','spill','snack','nap']:kid.id==='jax'?['snack','nap','spill','dance']:kid.id==='arianna'?['fort','cook','laundry','snack','art']:['bath','dance','spill','nap','snack'];type=bag[Math.floor(Math.random()*bag.length)]}
 const t=makeTask(++sequence,type,kids.indexOf(kid),cozy,day);tasks.push(t);kid.task=t;kid.path=[];if(type==='cook'||type==='laundry'){kid.path=nav.path(kid,type==='cook'?PLACES.cook:PLACES.laundry)}effects.begin(t,kid);toast(kid.lines[Math.floor(Math.random()*kid.lines.length)]);updateTasks();
}
function step(t){return taskStep(t,kids[t.kid])}
function choose(id){const t=tasks.find(t=>t.id===id);if(!t)return;socialActive=false;socialWork=0;selected=t;const s=step(t);player.path=nav.path(player,s);updateTasks();chime();}
function updateTasks(){
 const container=$('tasks');const ids=new Set(tasks.map(t=>String(t.id)));for(const el of [...container.children])if(!ids.has(el.dataset.id))el.remove();
 for(const t of tasks){const kid=kids[t.kid],e=EVENTS[t.type];let button=container.querySelector('[data-id="'+t.id+'"]');if(!button){button=document.createElement('button');button.dataset.id=t.id;button.innerHTML='<span class="icon"><span>'+e.icon+'</span></span><b>'+kid.name+'</b>';button.addEventListener('click',()=>choose(t.id));container.append(button)}button.className='task'+(selected===t?' active':'')+(t.remaining<12&&!cozy?' urgent':'');button.style.setProperty('--remaining',Math.max(0,t.remaining/t.total)*100+'%');button.setAttribute('aria-label',kid.name+': '+e.title+'. '+step(t).verb+(cozy?'':'. '+Math.ceil(t.remaining)+' seconds left'));}
 for(const k of kids){k.label.el.className='label';k.label.el.textContent=k.sleep>0?'💤 '+k.name:k.name}
}

function finish(t){const k=kids[t.kid];tasks=tasks.filter(x=>x!==t);k.task=null;k.follow=false;k.timer=6+Math.random()*5;if(t.type==='nap'){k.sleep=24;k.rest='sleep'}if(t.type==='snack'){k.sleep=6;k.rest='eat'}k.action=null;if(t.type!=='nap')k.seat=null;k.celebrate=2;effects.remove(t,k,true);effects.hold(player,null);completed++;combo++;const earned=10+Math.min(combo-1,5)*2;score+=earned;happiness=Math.min(100,happiness+6);selected=null;player.path=[];chime();toast('+'+earned+' ★  '+k.name+' is happy!');updateTasks()}
function expire(t){const k=kids[t.kid];effects.remove(t,k,false);k.action=null;k.seat=null;k.task=null;k.follow=false;k.timer=8;tasks=tasks.filter(x=>x!==t);if(selected===t){selected=null;player.path=[]}missed++;combo=0;happiness=Math.max(10,happiness-12);toast('Oops, '+k.name+'! We’ll try again.');chime(false);updateTasks()}
function end(){running=false;hold=false;player.path=[];const stars=rating(completed,missed);let best=score;try{best=Math.max(score,Number(localStorage.getItem('littleChaosBest')||0));localStorage.setItem('littleChaosBest',String(best))}catch{}$('endStars').textContent='★'.repeat(stars)+'☆'.repeat(3-stars);$('results').textContent=`${completed} little crises solved · ${score} happy stars. ${missed===0?'No mess left behind!':missed+' bigger messes—and plenty of love.'} Best day: ${best} stars.`;$('endOverlay').classList.remove('hidden');chime()}
function setPaused(value){if(!running)return;paused=value;hold=false;keys.clear();joy.x=joy.z=0;$('knob').style.transform='';$('pauseOverlay').classList.toggle('hidden',!value)}
$('start').addEventListener('click',()=>start(false));$('cozy').onclick=()=>start(true);$('pause').onclick=()=>setPaused(true);$('resume').onclick=()=>setPaused(false);$('restart').onclick=()=>start(cozy);$('next').onclick=()=>{day=Math.min(day+1,7);start(cozy)};$('again').onclick=()=>start(cozy);$('sound').onclick=()=>{soundOn=!soundOn;$('sound').textContent='Sound: '+(soundOn?'on':'off');chime()};$('quality').onclick=()=>{lowQuality=!lowQuality;renderer.setPixelRatio(lowQuality?1:Math.min(devicePixelRatio,1.5));resize();$('quality').textContent='Graphics: '+(lowQuality?'battery saver':'balanced')};
document.addEventListener('visibilitychange',()=>{if(document.hidden)setPaused(true)});window.addEventListener('blur',()=>{keys.clear();hold=false;joy.x=joy.z=0});
const keys=new Set(),joy={x:0,z:0};window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'){setPaused(!paused);return}if(!running||paused)return;keys.add(e.code);if(e.code==='Space')hold=true;if(e.code==='KeyP')postButton.click();if(e.code.startsWith('Digit')){const t=tasks[Number(e.code.slice(5))-1];if(t)choose(t.id)}});window.addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='Space')hold=false});
$('help').addEventListener('pointerdown',e=>{e.preventDefault();if(!running||paused)return;hold=true;$('help').setPointerCapture(e.pointerId)});for(const event of ['pointerup','pointercancel','lostpointercapture'])$('help').addEventListener(event,()=>hold=false);
let stickId=null;function joystick(e){if(e.pointerId!==stickId)return;const r=$('stick').getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dz=e.clientY-r.top-r.height/2,len=Math.hypot(dx,dz),m=Math.min(1,35/(len||1));joy.x=dx*m/35;joy.z=dz*m/35;$('knob').style.transform=`translate(${dx*m}px,${dz*m}px)`;player.path=[]}
$('stick').addEventListener('pointerdown',e=>{if(!running||paused)return;stickId=e.pointerId;$('stick').setPointerCapture(e.pointerId);joystick(e)});$('stick').addEventListener('pointermove',joystick);for(const event of ['pointerup','pointercancel','lostpointercapture'])$('stick').addEventListener(event,()=>{stickId=null;joy.x=joy.z=0;$('knob').style.transform=''});
const ray=new THREE.Raycaster(),ground=new THREE.Plane(new THREE.Vector3(0,1,0),0);$('game').addEventListener('pointerdown',e=>{if(!running||paused)return;const r=$('game').getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const p=new THREE.Vector3();if(ray.ray.intersectPlane(ground,p)){const t=tasks.find(t=>Math.hypot(step(t).x-p.x,step(t).z-p.z)<1.25);if(t)choose(t.id);else player.path=nav.path(player,p)}});
function move(a,dx,dz,dt,speed){const length=Math.hypot(dx,dz);if(length<.01){a.moving=false;return}dx/=length;dz/=length;const d=Math.min(speed*dt,length);let moved=false;if(!nav.blocked(a.x+dx*d,a.z)){a.x+=dx*d;moved=true}if(!nav.blocked(a.x,a.z+dz*d)){a.z+=dz*d;moved=true}a.moving=moved;if(moved)a.object.rotation.y=Math.atan2(dx,dz)}
function followPath(a,dt,speed){if(!a.path.length){a.moving=false;return}const p=a.path[0];move(a,p.x-a.x,p.z-a.z,dt,speed);if(Math.hypot(a.x-p.x,a.z-p.z)<.08)a.path.shift()}
function update(dt){elapsed+=dt;if(!cozy)seconds=Math.max(0,seconds-dt);if(seconds<=0){end();return}spawnIn-=dt;if(spawnIn<=0){spawn();spawnIn=Math.max(7,14-day)+Math.random()*4}
 const dx=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+joy.x,dz=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+joy.z;
 if(Math.hypot(dx,dz)>.12){socialActive=false;socialWork=0;player.path=[];move(player,(dx+dz)*Math.SQRT1_2,(-dx+dz)*Math.SQRT1_2,dt,3.5)}else followPath(player,dt,3.5);
 for(const k of kids){if(k.follow){if(Math.hypot(k.x-player.x,k.z-player.z)>1){k.timer-=dt;if(k.timer<=0){k.path=nav.path(k,player);k.timer=.5}followPath(k,dt,3.9)}else k.moving=false;continue}if(k.task||k.sleep>0){k.sleep=Math.max(0,k.sleep-dt);if(k.task&&k.path.length)followPath(k,dt,k.speed);else k.moving=false;continue}k.rest=null;k.action=null;k.seat=null;k.timer-=dt;if(k.timer<=0&&!k.path.length){let r;if(k.id==='lilah'&&Math.random()<.6){const sister=kids[2];r={x:sister.x,z:sister.z}}else r=rooms[Math.floor(Math.random()*rooms.length)];k.path=nav.path(k,{x:r.x+(Math.random()-.5)*2,z:r.z+(Math.random()-.5)*2});k.timer=5+Math.random()*8}followPath(k,dt,k.speed)}
 for(const t of [...tasks]){if(!cozy){t.remaining-=dt;if(t.remaining<=0)expire(t)}}
 if(!selected&&hold){const close=tasks.find(t=>Math.hypot(step(t).x-player.x,step(t).z-player.z)<.85);if(close){selected=close;updateTasks()}}
 let working=false;player.action=null;for(const k of kids)if(k.task)k.action=k.task.type==='dance'?'dance':null;
 socialCooldown=Math.max(0,socialCooldown-dt);postButton.disabled=socialCooldown>0;postButton.textContent=socialCooldown>0?Math.ceil(socialCooldown):'📱';postButton.classList.toggle('active',socialActive);postButton.hidden=!running;
 if(socialActive){$('instruction').textContent='Hold for a MomLife selfie';if(hold&&!player.moving){working=true;player.action='selfie';socialWork+=dt;effects.hold(player,'phone');const photobomber=kids.find(k=>Math.hypot(k.x-player.x,k.z-player.z)<2.5&&k.sleep<=0);if(photobomber)photobomber.action='cheer';if(socialWork>=3.5){socialActive=false;socialCooldown=40;posts++;score+=5;effects.burst(player.x,player.z);toast('Posted! '+captions[(posts-1)%captions.length]);chime();}}$('work').style.width=socialWork/3.5*100+'%';}
 else if(selected){const t=selected,k=kids[t.kid],s=step(t),near=Math.hypot(s.x-player.x,s.z-player.z)<.85,childReady=!((t.type==='snack'&&t.stage===2)||(t.type==='bath'&&t.stage>0)||(t.type==='nap'&&t.stage>0))||Math.hypot(k.x-player.x,k.z-player.z)<1.9;
 $('where').textContent=s.name.toUpperCase();$('instruction').textContent=!near?'Walking to '+s.name:!childReady?'Waiting for '+k.name:s.verb+' · hold';
 if(hold&&near&&childReady){player.path=[];player.moving=false;t.work+=dt;working=true;player.action=choreMode(t.type,t.stage);const helper=kids[2];if(helper!==k&&!helper.task&&helper.sleep<=0&&Math.hypot(helper.x-player.x,helper.z-player.z)<2.5){t.work+=dt*.25;helper.path=[];helper.moving=false;helper.action=player.action;if(!t.assisted){t.assisted=true;toast('Arianna: I am the assistant manager!')}}if(t.type==='nap'&&t.stage>0)k.seat=k.id==='harper'?{x:-7.4,y:1,z:8.75,lying:true}:k.id==='arianna'?{x:-3.9,y:.92,z:-.4,lying:true,rotation:Math.PI/2}:k.id==='lilah'?{x:-1.85,y:1,z:8.9,lying:true}:{x:.7,y:1,z:9.05,lying:true};if(t.type==='bath'&&t.stage===1)k.seat={x:-11.1,y:.65,z:-.65};if(t.type==='bath'&&t.stage===2)k.seat=null;k.action=t.type==='snack'&&t.stage===2?'eat':t.type==='nap'&&t.stage>0?'sleep':t.type==='dance'?'dance':'cheer';
 const face=t.type==='cook'?{x:-6,z:-7.35}:t.type==='bath'&&t.stage>0?{x:-11.1,z:-.65}:t.type==='snack'&&t.stage===0?{x:-4.5,z:-4.5}:(k.seat??k);player.object.rotation.y=Math.atan2(face.x-player.x,face.z-player.z);
 if(t.work>=s.duration){if(advanceTask(t)){finish(t)}else{if((t.type==='snack'&&t.stage===2)||(t.type==='bath'&&t.stage===1)||(t.type==='nap'&&t.stage===1)){k.follow=true;k.timer=0}if(t.type==='nap'&&t.stage===2)k.follow=false;choose(t.id);}}}
 $('work').style.width=t.work/s.duration*100+'%';
 }else{$('instruction').textContent=elapsed<8?'Tap a need to help.':'';$('work').style.width='0%'}
 const mode=player.action;const carry=mode==='selfie'?'phone':mode==='stir'?'spoon':mode==='wipe'?'brush':mode==='story'?'book':mode==='fold'?'sock':mode==='slice'||(selected?.type==='snack'&&selected.stage>0)?'plate':selected?.type==='nap'?'teddy':null;effects.hold(player,carry);
 workingNow=working;effects.update(dt,tasks,kids,selected,working);$('help').classList.toggle('working',working);$('context').style.opacity=selected||socialActive||elapsed<8?'1':'0';$('help').querySelector('b').textContent=working?'HELPING…':'HOLD';
 $('time').textContent=cozy?'∞':Math.floor(seconds/60)+':'+String(Math.floor(seconds%60)).padStart(2,'0');$('day').textContent=`DAY ${day}${cozy?' · COZY':''}`;$('score').textContent='★ '+score;$('calm').style.width=happiness+'%';
}
const cameraFocus={x:0,z:0},dotMatrix=new THREE.Matrix4();
const halo=new THREE.Mesh(new THREE.RingGeometry(.38,.43,32),new THREE.MeshBasicMaterial({color:'#bf7d63',transparent:true,opacity:.8,side:THREE.DoubleSide,depthWrite:false}));halo.rotation.x=-Math.PI/2;halo.visible=false;world.add(halo);
const pathDots=new THREE.InstancedMesh(new THREE.SphereGeometry(.05,6,4),new THREE.MeshBasicMaterial({color:'#fff5dc'}),32);pathDots.count=0;pathDots.frustumCulled=false;world.add(pathDots);
let last=performance.now(),hudTick=0,frames=0,frameTime=0;
function frame(now){requestAnimationFrame(frame);const dt=Math.max(0,Math.min((now-last)/1000,.05));last=now;if(ready){if(running&&!paused){update(dt);hudTick+=dt;if(hudTick>.5){hudTick=0;updateTasks()}}for(const a of [player,...kids]){if(!paused)animateActor(a,running?dt:0,running?elapsed:0)}

 const targetX=closeView?player.x:-3,targetZ=closeView?player.z:-3;cameraFocus.x=THREE.MathUtils.damp(cameraFocus.x,targetX,7,dt);cameraFocus.z=THREE.MathUtils.damp(cameraFocus.z,targetZ,7,dt);camera.position.set(cameraFocus.x+18,20,cameraFocus.z+18);camera.lookAt(cameraFocus.x,0,cameraFocus.z);camera.updateMatrixWorld();
 const project=p=>{v.set(p.x,p.y,p.z).project(camera);return {x:(v.x*.5+.5)*width,y:(-v.y*.5+.5)*height}};
 for(const item of labelItems){const p=project(item.position());item.el.style.left=p.x+'px';item.el.style.top=p.y+'px';item.el.style.visibility=p.x<20||p.x>width-20||p.y<115||p.y>height-130?'hidden':'visible'}
 const placed=[];for(const t of [...tasks].sort((a,b)=>(b===selected)-(a===selected))){const kid=kids[t.kid],target=t===selected?step(t):kid,p=project({x:target.x,y:1.85,z:target.z}),el=$('tasks').querySelector('[data-id="'+t.id+'"]');if(!el)continue;el.style.visibility=t===selected&&Math.hypot(step(t).x-player.x,step(t).z-player.z)<.85?'hidden':'visible';const edge=p.x<32||p.x>width-32||p.y<130||p.y>height-140;let x=THREE.MathUtils.clamp(p.x,32,width-32),y=THREE.MathUtils.clamp(p.y,132,height-142);for(const q of placed){if(Math.abs(q.x-x)<53&&Math.abs(q.y-y)<62){y=q.y+64;if(y>height-140){y=q.y-64;x=THREE.MathUtils.clamp(x+55,32,width-32)}}}placed.push({x,y});el.classList.toggle('edge',edge);el.style.left=x+'px';el.style.top=y+'px';}
 const speech=project({x:player.x,y:2.6,z:player.z});$('toast').style.left=THREE.MathUtils.clamp(speech.x,105,width-105)+'px';$('toast').style.top=speech.y+'px';
 halo.visible=!!selected&&running;if(selected){const st=step(selected);halo.position.set(st.x,.13,st.z);halo.scale.setScalar(1+Math.sin(now*.004)*.08)}
 pathDots.count=Math.min(32,Math.ceil(player.path.length/4));for(let i=0;i<pathDots.count;i++){const q=player.path[i*4];dotMatrix.makeTranslation(q.x,.13,q.z);pathDots.setMatrixAt(i,dotMatrix)}pathDots.instanceMatrix.needsUpdate=true;
 if(now>toastUntil)$('toast').classList.remove('show');renderer.render(scene,camera);frames++;frameTime+=dt;}
}requestAnimationFrame(frame);
// Read-only diagnostics for smoke/performance checks; no test-only gameplay shortcuts.
window.littleChaos={get state(){return {ready,running,paused,cozy,day,seconds,score,happiness,completed,missed,posts,socialActive,effects:effects?.tasks.size,player:player?{x:player.x,z:player.z,path:player.path.length,animation:player.animationMode,held:player.heldName,arm:player.rig.armR?.rotation.x}:null,tasks:tasks.map(t=>({...t,target:step(t)})),kids:kids.map(k=>({id:k.id,x:k.x,z:k.z,following:k.follow,sleep:k.sleep,animation:k.animationMode,seated:!!k.seat})),drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,averageFPS:Math.round(frames/(frameTime||1))}}};
