import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {mergeVertices,mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {createNavigation} from './navigation.js';
import {KIDS,EVENTS,PLACES,makeTask,taskStep,advanceTask,rating} from './simulation.js';
import './style.css';
const $=id=>document.getElementById(id),app=$('app');
let renderer;try{renderer=new THREE.WebGLRenderer({canvas:$('game'),antialias:true,alpha:false,powerPreference:'high-performance'});}catch(e){$('start').textContent='This browser needs WebGL 2';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor('#dce8ce');
const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-8,8,14,-14,.1,100);camera.position.set(0,28,20);camera.lookAt(0,0,0);
scene.add(new THREE.HemisphereLight('#fff8e4','#b5c3a0',2.6));const sun=new THREE.DirectionalLight('#fff1d2',2.8);sun.position.set(-8,20,10);scene.add(sun);
const world=new THREE.Group();scene.add(world);
let width=400,height=800,closeView=false;function resize(){width=app.clientWidth;height=app.clientHeight;renderer.setSize(width,height,false);const vh=Math.max(27.8,14.8/(width/height))*(closeView?.6:1);camera.left=-vh*width/height/2;camera.right=-camera.left;camera.top=vh/2+1.6;camera.bottom=-vh/2+1.6;camera.updateProjectionMatrix();document.body.classList.toggle('landscape',innerWidth>innerHeight)}window.addEventListener('resize',resize);resize();
const viewButton=document.createElement('button');viewButton.id='view';viewButton.textContent='＋';viewButton.setAttribute('aria-label','Toggle close-up view');$('pause').before(viewButton);viewButton.onclick=()=>{closeView=!closeView;viewButton.textContent=closeView?'−':'＋';resize()};
// One shared soft contact-shadow texture, instead of expensive realtime shadow maps.
const sc=document.createElement('canvas');sc.width=sc.height=64;const ctx=sc.getContext('2d'),grad=ctx.createRadialGradient(32,32,3,32,32,30);grad.addColorStop(0,'rgba(65,61,41,.3)');grad.addColorStop(1,'rgba(65,61,41,0)');ctx.fillStyle=grad;ctx.fillRect(0,0,64,64);const shadowTex=new THREE.CanvasTexture(sc),shadowMat=new THREE.MeshBasicMaterial({map:shadowTex,transparent:true,depthWrite:false});
function shadow(x,z,size){const m=new THREE.Mesh(new THREE.PlaneGeometry(size,size),shadowMat);m.rotation.x=-Math.PI/2;m.position.set(x,.11,z);world.add(m);return m}
const labelItems=[];function label(text,position,cls=''){const el=document.createElement('div');el.className='label '+cls;el.textContent=text;$('labels').append(el);const item={el,position};labelItems.push(item);return item}
let nav,rooms,kids=[],player,ready=false,running=false,paused=false,cozy=false,day=1,seconds=180,happiness=100,score=0,completed=0,missed=0,combo=0,tasks=[],selected=null,sequence=0,spawnIn=9,elapsed=0,toastUntil=0,hold=false,soundOn=false,lowQuality=false;
let audioCtx;function chime(success=true){if(!soundOn)return;try{audioCtx??=new AudioContext();audioCtx.resume();for(let i=0;i<3;i++){const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.connect(g);g.connect(audioCtx.destination);o.type='sine';o.frequency.value=(success?523:220)*[1,1.25,1.5][i];const t=audioCtx.currentTime+i*.08;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.05,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+.2);o.start(t);o.stop(t+.22)}}catch{}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');toastUntil=performance.now()+4000}
const v=new THREE.Vector3();
const toyMaterial=new THREE.MeshLambertMaterial({vertexColors:true});
function optimize(root){root.updateMatrixWorld(true);const pieces=[];root.traverse(o=>{if(o.isMesh){const g=o.geometry.clone().applyMatrix4(o.matrixWorld).toNonIndexed();const c=o.material.color,colors=new Float32Array(g.attributes.position.count*3);for(let i=0;i<colors.length;i+=3){colors[i]=c.r;colors[i+1]=c.g;colors[i+2]=c.b}g.setAttribute('color',new THREE.BufferAttribute(colors,3));g.deleteAttribute('uv');g.deleteAttribute('tangent');g.clearGroups();pieces.push(g)}});const mesh=new THREE.Mesh(mergeVertices(mergeGeometries(pieces,false)),toyMaterial);root.clear();root.add(mesh);pieces.forEach(g=>g.dispose())}
const loader=new GLTFLoader();
async function init(){
 const [house,navigation,...models]=await Promise.all([loader.loadAsync('/assets/house.glb'),fetch('/assets/navigation.json').then(r=>{if(!r.ok)throw Error('Missing navigation');return r.json()}),...['kayla',...KIDS.map(k=>k.id)].map(n=>loader.loadAsync('/assets/'+n+'.glb'))]);
 optimize(house.scene);world.add(house.scene);rooms=navigation.rooms;nav=createNavigation(navigation.obstacles);
 for(const [x,z,w,d] of navigation.obstacles){if(w>.5&&d>.4)shadow(x,z,Math.max(w,d)*1.35)}
 rooms.forEach(r=>label(r.name.toUpperCase(),()=>({x:r.x,y:.18,z:r.z+1.96}),'room-label'));
 function actor(model,name,x,z,scale=1){optimize(model.scene);const object=model.scene;object.position.set(x,0,z);object.scale.setScalar(scale);world.add(object);const a={object,name,x,z,path:[],phase:Math.random()*6,moving:false,shadow:shadow(x,z,.85)};a.label=label(name,()=>({x:a.x,y:name==='Kayla'?1.95:1.5,z:a.z}),name==='Kayla'?'kayla':'');return a}
 player=actor(models[0],'Kayla',0,0);kids=KIDS.map((k,i)=>{const r=rooms[k.room],p=nav.nearest({x:r.x+1,z:r.z+.5+i*.22});return {...actor(models[i+1],k.name,p.x,p.z),...k,timer:3+i*2,task:null,sleep:0,follow:false}});
 ready=true;$('start').disabled=$('cozy').disabled=false;$('start').textContent='Let the little chaos begin →';renderer.render(scene,camera);
}
init().catch(error=>{console.error(error);$('start').textContent='Couldn’t load the house · tap to retry';$('start').disabled=false;$('start').onclick=()=>location.reload();toast('Asset loading failed. Check your connection and try again.');});
function start(isCozy=false){if(!ready)return;cozy=isCozy;running=true;paused=false;seconds=180;happiness=100;score=completed=missed=combo=elapsed=0;tasks=[];selected=null;sequence=0;spawnIn=10;player.x=0;player.z=0;player.path=[];kids.forEach(k=>{k.task=null;k.sleep=0;k.follow=false;k.path=[];k.timer=4;const p=nav.nearest({x:rooms[k.room].x+1,z:rooms[k.room].z+.8});k.x=p.x;k.z=p.z});for(const id of ['overlay','pauseOverlay','endOverlay'])$(id).classList.add('hidden');spawn('snack',1);spawn('art',0);toast('Tap a task card, then hold HELP when Kayla arrives.');updateTasks();}
function spawn(type,index){if(tasks.length>=5)return;let kid=index===undefined?kids.filter(k=>!k.task&&k.sleep<=0)[Math.floor(Math.random()*kids.filter(k=>!k.task&&k.sleep<=0).length)]:kids[index];if(!kid)return;
 if(!type){const bag=kid.id==='harper'?['art','dance','spill','snack','nap']:kid.id==='jax'?['snack','nap','spill','dance']:kid.id==='arianna'?['fort','cook','laundry','snack','art']:['bath','dance','spill','nap','snack'];type=bag[Math.floor(Math.random()*bag.length)]}
 const t=makeTask(++sequence,type,kids.indexOf(kid),cozy,day);tasks.push(t);kid.task=t;kid.path=[];if(type==='cook'||type==='laundry'){const p=nav.nearest(type==='cook'?PLACES.kitchen:PLACES.laundry);kid.x=p.x;kid.z=p.z}updateTasks();if(elapsed>2)toast(kid.name+': “'+kid.lines[Math.floor(Math.random()*kid.lines.length)]+'”');
}
function step(t){return taskStep(t,kids[t.kid])}
function choose(id){const t=tasks.find(t=>t.id===id);if(!t)return;selected=t;const s=step(t);player.path=nav.path(player,s);updateTasks();chime();}
function updateTasks(){const container=$('tasks');container.replaceChildren();for(const t of tasks){const kid=kids[t.kid],e=EVENTS[t.type],button=document.createElement('button');button.className='task'+(selected===t?' active':'')+(t.remaining<12?' urgent':'');button.dataset.id=t.id;button.innerHTML=`<span class="icon">${e.icon}</span><div><b>${kid.name} · ${e.title}</b><small>${cozy?'Take your time':Math.ceil(t.remaining)+'s'} · ${t.stage+1}/${e.steps}</small></div><i class="timer" style="width:${t.remaining/t.total*100}%"></i>`;button.addEventListener('click',()=>choose(t.id));container.append(button)}for(const k of kids){k.label.el.className='label '+(k.task?'bubble':'');k.label.el.textContent=k.sleep>0?'💤 '+k.name:k.task?EVENTS[k.task.type].icon:k.name}}
function finish(t){const k=kids[t.kid];tasks=tasks.filter(x=>x!==t);k.task=null;k.follow=false;k.timer=6+Math.random()*5;if(t.type==='nap')k.sleep=24;if(t.type==='snack')k.sleep=6;completed++;combo++;const earned=10+Math.min(combo-1,5)*2;score+=earned;happiness=Math.min(100,happiness+6);selected=null;player.path=[];chime();toast(['Tiny crisis, big cuddle!','Kayla saves the day. Again.','That’s one happy little human!','A gold star for the grown-up!'][completed%4]+` +${earned} ★`);updateTasks()}
function expire(t){const k=kids[t.kid];k.task=null;k.follow=false;k.timer=8;tasks=tasks.filter(x=>x!==t);if(selected===t){selected=null;player.path=[]}missed++;combo=0;happiness=Math.max(10,happiness-12);toast(k.name+' made a bigger mess. Deep breath—keep going!');chime(false);updateTasks()}
function end(){running=false;hold=false;player.path=[];const stars=rating(completed,missed);let best=score;try{best=Math.max(score,Number(localStorage.getItem('littleChaosBest')||0));localStorage.setItem('littleChaosBest',String(best))}catch{}$('endStars').textContent='★'.repeat(stars)+'☆'.repeat(3-stars);$('results').textContent=`${completed} little crises solved · ${score} happy stars. ${missed===0?'No mess left behind!':missed+' bigger messes—and plenty of love.'} Best day: ${best} stars.`;$('endOverlay').classList.remove('hidden');chime()}
function setPaused(value){if(!running)return;paused=value;hold=false;keys.clear();joy.x=joy.z=0;$('knob').style.transform='';$('pauseOverlay').classList.toggle('hidden',!value)}
$('start').addEventListener('click',()=>start(false));$('cozy').onclick=()=>start(true);$('pause').onclick=()=>setPaused(true);$('resume').onclick=()=>setPaused(false);$('restart').onclick=()=>start(cozy);$('next').onclick=()=>{day=Math.min(day+1,7);start(cozy)};$('again').onclick=()=>start(cozy);$('sound').onclick=()=>{soundOn=!soundOn;$('sound').textContent='Sound: '+(soundOn?'on':'off');chime()};$('quality').onclick=()=>{lowQuality=!lowQuality;renderer.setPixelRatio(lowQuality?1:Math.min(devicePixelRatio,1.5));resize();$('quality').textContent='Graphics: '+(lowQuality?'battery saver':'balanced')};
document.addEventListener('visibilitychange',()=>{if(document.hidden)setPaused(true)});window.addEventListener('blur',()=>{keys.clear();hold=false;joy.x=joy.z=0});
const keys=new Set(),joy={x:0,z:0};window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'){setPaused(!paused);return}if(!running||paused)return;keys.add(e.code);if(e.code==='Space')hold=true;if(e.code.startsWith('Digit')){const t=tasks[Number(e.code.slice(5))-1];if(t)choose(t.id)}});window.addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='Space')hold=false});
$('help').addEventListener('pointerdown',e=>{e.preventDefault();if(!running||paused)return;hold=true;$('help').setPointerCapture(e.pointerId)});for(const event of ['pointerup','pointercancel','lostpointercapture'])$('help').addEventListener(event,()=>hold=false);
let stickId=null;function joystick(e){if(e.pointerId!==stickId)return;const r=$('stick').getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dz=e.clientY-r.top-r.height/2,len=Math.hypot(dx,dz),m=Math.min(1,35/(len||1));joy.x=dx*m/35;joy.z=dz*m/35;$('knob').style.transform=`translate(${dx*m}px,${dz*m}px)`;player.path=[]}
$('stick').addEventListener('pointerdown',e=>{if(!running||paused)return;stickId=e.pointerId;$('stick').setPointerCapture(e.pointerId);joystick(e)});$('stick').addEventListener('pointermove',joystick);for(const event of ['pointerup','pointercancel','lostpointercapture'])$('stick').addEventListener(event,()=>{stickId=null;joy.x=joy.z=0;$('knob').style.transform=''});
const ray=new THREE.Raycaster(),ground=new THREE.Plane(new THREE.Vector3(0,1,0),0);$('game').addEventListener('pointerdown',e=>{if(!running||paused)return;const r=$('game').getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const p=new THREE.Vector3();if(ray.ray.intersectPlane(ground,p)){const t=tasks.find(t=>Math.hypot(step(t).x-p.x,step(t).z-p.z)<1.25);if(t)choose(t.id);else player.path=nav.path(player,p)}});
function move(a,dx,dz,dt,speed){const length=Math.hypot(dx,dz);if(length<.01){a.moving=false;return}dx/=length;dz/=length;const d=Math.min(speed*dt,length);let moved=false;if(!nav.blocked(a.x+dx*d,a.z)){a.x+=dx*d;moved=true}if(!nav.blocked(a.x,a.z+dz*d)){a.z+=dz*d;moved=true}a.moving=moved;if(moved)a.object.rotation.y=Math.atan2(dx,dz)}
function followPath(a,dt,speed){if(!a.path.length){a.moving=false;return}const p=a.path[0];move(a,p.x-a.x,p.z-a.z,dt,speed);if(Math.hypot(a.x-p.x,a.z-p.z)<.08)a.path.shift()}
function update(dt){elapsed+=dt;if(!cozy)seconds=Math.max(0,seconds-dt);if(seconds<=0){end();return}spawnIn-=dt;if(spawnIn<=0){spawn();spawnIn=Math.max(7,14-day)+Math.random()*4}
 const dx=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+joy.x,dz=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+joy.z;
 if(Math.hypot(dx,dz)>.12){player.path=[];move(player,dx,dz,dt,3.5)}else followPath(player,dt,3.5);
 for(const k of kids){if(k.follow){if(Math.hypot(k.x-player.x,k.z-player.z)>1){k.timer-=dt;if(k.timer<=0){k.path=nav.path(k,player);k.timer=.5}followPath(k,dt,3.9)}else k.moving=false;continue}if(k.task||k.sleep>0){k.sleep=Math.max(0,k.sleep-dt);k.moving=false;continue}k.timer-=dt;if(k.timer<=0&&!k.path.length){let r;if(k.id==='lilah'&&Math.random()<.6){const sister=kids[2];r={x:sister.x,z:sister.z}}else r=rooms[Math.floor(Math.random()*rooms.length)];k.path=nav.path(k,{x:r.x+(Math.random()-.5)*2,z:r.z+(Math.random()-.5)*2});k.timer=5+Math.random()*8}followPath(k,dt,k.speed)}
 for(const t of [...tasks]){if(!cozy){t.remaining-=dt;if(t.remaining<=0)expire(t)}}
 if(!selected&&hold){const close=tasks.find(t=>Math.hypot(step(t).x-player.x,step(t).z-player.z)<.85);if(close){selected=close;updateTasks()}}
 let working=false;if(selected){const t=selected,k=kids[t.kid],s=step(t),near=Math.hypot(s.x-player.x,s.z-player.z)<.85;$('where').textContent=s.name.toUpperCase();$('instruction').textContent=near?s.verb+' · hold HELP':'On our way: '+s.verb.toLowerCase();if(hold&&near){player.path=[];t.work+=dt;working=true;if(t.work>=s.duration){if(advanceTask(t)){finish(t)}else{if((t.type==='snack'&&t.stage===2)||(t.type==='bath'&&t.stage===1)||(t.type==='nap'&&t.stage===1)){k.follow=true;k.timer=0}if(t.type==='nap'&&t.stage===2)k.follow=false;choose(t.id);toast('Nice! Next: '+step(t).verb.toLowerCase()+'.')}}}$('work').style.width=(t.work/s.duration*100)+'%'}else{$('where').textContent=cozy?'COZY MODE · NO RUSH':'ONE LITTLE THING AT A TIME';$('instruction').textContent=tasks.length?'Tap a task card to help a little human.':'A rare moment of peace. Enjoy it!';$('work').style.width='0%'}$('help').classList.toggle('working',working);
 $('time').textContent=cozy?'∞':Math.floor(seconds/60)+':'+String(Math.floor(seconds%60)).padStart(2,'0');$('day').textContent=`DAY ${day} · ${cozy?'COZY MODE':'A FULL HOUSE'}`;$('score').textContent='★ '+score;$('calm').style.width=happiness+'%';
}
let last=performance.now(),hudTick=0,frames=0,frameTime=0;
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;if(ready){if(running&&!paused){update(dt);hudTick+=dt;if(hudTick>.5){hudTick=0;updateTasks()}}for(const a of [player,...kids]){if(running&&!paused)a.phase+=dt*(a.moving?14:2);a.object.position.set(a.x,a.moving?Math.sin(a.phase)*.045:Math.sin(a.phase)*.012,a.z);a.object.rotation.z=a.moving?Math.sin(a.phase)*.055:0;a.shadow.position.x=a.x;a.shadow.position.z=a.z}
 const cx=closeView?player.x:0,cz=closeView?player.z:0;camera.position.set(cx,28,cz+20);camera.lookAt(cx,0,cz);camera.updateMatrixWorld();
 for(const item of labelItems){const p=item.position();v.set(p.x,p.y,p.z).project(camera);item.el.style.left=((v.x*.5+.5)*width)+'px';item.el.style.top=((-v.y*.5+.5)*height)+'px';item.el.style.visibility=v.x<-.95||v.x>.95||v.y<-.55||v.y>.49?'hidden':'visible'}
 if(now>toastUntil)$('toast').classList.remove('show');renderer.render(scene,camera);frames++;frameTime+=dt;}
}requestAnimationFrame(frame);
// Read-only diagnostics for smoke/performance checks; no test-only gameplay shortcuts.
window.littleChaos={get state(){return {ready,running,paused,cozy,day,seconds,score,happiness,completed,missed,player:player?{x:player.x,z:player.z,path:player.path.length}:null,tasks:tasks.map(t=>({...t,target:step(t)})),kids:kids.map(k=>({id:k.id,x:k.x,z:k.z,following:k.follow,sleep:k.sleep})),drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,averageFPS:Math.round(frames/(frameTime||1))}}};
