export const KIDS=[{id:'harper',name:'Harper',age:'4',trait:'The make-believe queen',emoji:'🎨',speed:1.25,room:4,color:'#d48eae',lines:['The carpet is an ocean!','My teddy is the mayor.','It’s a rainbow emergency!']},{id:'jax',name:'Jax',age:'1½',trait:'Tiny feet. Giant curiosity.',emoji:'🦖',speed:.8,room:5,color:'#90b5a4',lines:['Nana? NANA!','Roaaaar!','Uh-oh. Again!']},{id:'arianna',name:'Arianna',age:'7',trait:'The very confident helper',emoji:'🌟',speed:1.5,room:3,color:'#e3bf65',lines:['I invented indoor camping!','I can do it all by myself!','My restaurant has ONE star. Me.']},{id:'lilah',name:'Lilah',age:'2',trait:'Whatever her sister is doing',emoji:'🫧',speed:.95,room:5,color:'#aa9bc6',lines:['Me too! Me too!','Bubbles go POP!','Arianna said so!']}];
export const PLACES={kitchen:{x:-4.5,z:-3.2,name:'Kitchen'},cook:{x:-6,z:-6.1,name:'Kitchen'},dining:{x:1.3,z:-4.1,name:'Dining room'},bath:{x:-10.7,z:.7,name:'Bathroom'},laundry:{x:-10.4,z:-5,name:'Laundry'},bed:{x:-.5,z:6.5,name:'Nursery'},play:{x:4,z:1.8,name:'Play studio'}};
export const EVENTS={snack:{icon:'🍌',title:'Snack attack',verb:'Slice the fruit',duration:2.4,limit:70,steps:3},bath:{icon:'🫧',title:'Bubble beard',verb:'Gather bath toys',duration:2.2,limit:75,steps:3},nap:{icon:'💤',title:'Sleepy pickle',verb:'Find the teddy',duration:2,limit:70,steps:3},art:{icon:'🎨',title:'Crayon ocean',verb:'Wipe the rainbow',duration:3.1,limit:38,steps:1},fort:{icon:'⛺',title:'Sofa spaceship',verb:'Land the spaceship',duration:3.5,limit:42,steps:1},laundry:{icon:'🧦',title:'Sock confetti',verb:'Catch the socks',duration:2.8,limit:40,steps:1},dance:{icon:'🎵',title:'Wiggle emergency',verb:'Do the silly dance',duration:2.5,limit:37,steps:1},cook:{icon:'🍲',title:'Soup surprise',verb:'Stir the soup',duration:3,limit:42,steps:1},spill:{icon:'🧃',title:'Juice puddle',verb:'Mop it up',duration:2.8,limit:36,steps:1}};
export function makeTask(id,type,kid,cozy=false,day=1){const e=EVENTS[type];return {id,type,kid,stage:0,work:0,total:Math.max(28,e.limit-(day-1)*2),remaining:Math.max(28,e.limit-(day-1)*2),cozy,done:false};}
export function taskStep(t,kid){const e=EVENTS[t.type];
  if(t.type==='snack')return [{...PLACES.kitchen,verb:'Slice a banana',duration:2.3},{x:kid.x,z:kid.z,name:kid.name,verb:'Invite to snack time',duration:1},{...PLACES.dining,verb:'Serve a happy snack',duration:2.5}][t.stage];
  if(t.type==='bath')return [{x:kid.x,z:kid.z,name:kid.name,verb:'Round up the bubble explorer',duration:1.3},{...PLACES.bath,verb:'Pop, scrub & giggle',duration:3.3},{...PLACES.bath,verb:'Wrap in a fluffy towel',duration:1.8}][t.stage];
  if(t.type==='nap'){const bed=kid.id==='harper'?{x:-5.8,z:7,name:'Harper’s room'}:kid.id==='arianna'?{x:-4,z:.2,name:'Living room'}:PLACES.bed;return [{x:kid.x,z:kid.z,name:kid.name,verb:'Find the favorite teddy',duration:1.6},{...bed,verb:'Tuck in the sleepy pickle',duration:2.5},{...bed,verb:'Whisper a bedtime story',duration:2}][t.stage];}
  if(t.type==='cook')return {...PLACES.cook,verb:e.verb,duration:e.duration};
  if(t.type==='laundry')return {...PLACES.laundry,verb:e.verb,duration:e.duration};
  return {x:kid.x,z:kid.z,name:kid.name,verb:e.verb,duration:e.duration};
}
export function advanceTask(t){t.work=0;t.stage++;t.done=t.stage>=EVENTS[t.type].steps;return t.done}
export function rating(completed,missed){return completed>=9&&missed<=2?3:completed>=5?2:1}
